Integration specs for views and fix n+1 problems
duskotmane/blog-app pull request #10
Opened 2023-09-14 05:15 UTC by otmaneechchafyky

# Features ⭐ ⭐ ⭐ 

- [ ] Make sure that the N+1 problem is solved when fetching all posts and their comments for a user.
 - Before fixing n+1 problems:
    
![bef](https://github.com/otmaneechchafyky/blog-app/assets/70438968/0595877d-8612-4182-aedf-5706c2a4e417)

 - After fixing n+1 problems:
  
![after](https://github.com/otmaneechchafyky/blog-app/assets/70438968/978e416f-d923-46f5-834a-02d80f5e3575)

- [ ] Use Capybara to write integration tests for each view in your project.
    - Think on the flow of things and group the tests of page in a way that makes sense. For example, one test would check for 
      the things in the page and another test for clicking links on it.

    - User index page:
       - I can see the username of all other users.
       - I can see the profile picture for each user.
       - I can see the number of posts each user has written.
       - When I click on a user, I am redirected to that user's show page.

   - User show page:
     - I can see the user's profile picture.
     - I can see the user's username.
     - I can see the number of posts the user has written.
     - I can see the user's bio.
     - I can see the user's first 3 posts.
     - I can see a button that lets me view all of a user's posts.
     - When I click a user's post, it redirects me to that post's show page.
     - When I click to see all posts, it redirects me to the user's post's index page.

   - User post index page:
     - I can see the user's profile picture.
     - I can see the user's username.
     - I can see the number of posts the user has written.
     - I can see a post's title.
     - I can see some of the post's body.
     - I can see the first comments on a post.
     - I can see how many comments a post has.
     - I can see how many likes a post has.
     - I can see a section for pagination if there are more posts than fit on the view.
     - When I click on a post, it redirects me to that post's show page.

  - Post show page:
     - I can see the post's title.
     - I can see who wrote the post.
     - I can see how many comments it has.
     - I can see how many likes it has.
     - I can see the post body.
     - I can see the username of each commentor.
     - I can see the comment each commentor left.

2023-09-14 06:16 UTC, Ibizugbe requested changes
Hi @otmaneechchafyky 👋🏼👋🏼, 

![require_changes](https://github.com/otmaneechchafyky/blog-app/assets/64643995/c8532c98-ab15-45c3-a358-1aa41d88db58)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅

- [x] Test cases have been written to check username of all users👍🏼.
- [x] Gem file has capybare gem for testing👍🏼.
- [x] gitflow is used👍🏼


## Required Changes ♻️

- [x] Kindly note that some of your test cases are failing, do well to ensure all tests are passing before proceeding to submit, to avoid blockers😉.
<img width="866" alt="image" src="https://github.com/otmaneechchafyky/blog-app/assets/64643995/28df0291-71ff-4ff6-ac05-a167bb0842d8">


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-14 06:16 UTC, Ibizugbe commented on spec/views/user_show_spec.rb
> +  end
I noticed you didn't implement a test for showing the users first 3 posts, Kindly do well to implement that as it is a requirement😉.
<img width="521" alt="image" src="https://github.com/otmaneechchafyky/blog-app/assets/64643995/8ed76f49-6b4f-4d62-a17d-9d2c76c762ab">

2023-09-14 06:16 UTC, Ibizugbe commented on spec/views/post_index_spec.rb
> +    expect(page).to have_content("first post's title")
Nice job so far😉. Kindly do well in writing a pagination test, as this is also a requirement👍🏼.
<img width="658" alt="image" src="https://github.com/otmaneechchafyky/blog-app/assets/64643995/6c9fa6d6-4d15-4f70-8ddc-d08c3e924268">

2023-09-14 07:21 UTC, otmaneechchafyky commented on spec/views/user_show_spec.rb
> +  end
I added it 😃

2023-09-15 15:13 UTC, IngDavidTM approved these changes
Hi @otmaneechchafyky 🙋‍♂️, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request follows the GitFlow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-16 07:33 UTC, merged